from PyQt5 import QtCore, QtGui, QtWidgets

a = 0

class Ui_Dialog(object):
    def jop(self):
        global a
        if self.radioButton.isChecked():
                a += 25
        if self.radioButton_5.isChecked():
                a += 25
        if self.radioButton_7.isChecked():
                a += 25
        if self.radioButton_9.isChecked():
                a += 25
        self.progressBar.show()
        self.progressBar.setValue(a)
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(698, 388)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 90, 341, 21))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton_2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_2.setStyleSheet("color:white;")
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_2.addWidget(self.radioButton_2)
        self.radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton.setStyleSheet("color:white;")
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_2.addWidget(self.radioButton)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 180, 261, 21))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton_5 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioButton_5.setStyleSheet("color:white;")
        self.radioButton_5.setObjectName("radioButton_5")
        self.horizontalLayout_3.addWidget(self.radioButton_5)
        self.radioButton_4 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioButton_4.setStyleSheet("color:white;")
        self.radioButton_4.setObjectName("radioButton_4")
        self.horizontalLayout_3.addWidget(self.radioButton_4)
        self.radioButton_3 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioButton_3.setStyleSheet("color:white;")
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_3.addWidget(self.radioButton_3)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 260, 231, 19))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioButton_7 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.radioButton_7.setStyleSheet("color:white;")
        self.radioButton_7.setObjectName("radioButton_7")
        self.horizontalLayout_4.addWidget(self.radioButton_7)
        self.radioButton_6 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.radioButton_6.setStyleSheet("color:white;")
        self.radioButton_6.setObjectName("radioButton_6")
        self.horizontalLayout_4.addWidget(self.radioButton_6)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 700, 393))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(r"C:\Users\777\Desktop\psp\python\pyqtdesign\3.jpg"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:white;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:white;\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 140, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:white;\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 230, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:white;\n"
"")
        self.label_5.setObjectName("label_5")
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(490, 20, 118, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 300, 371, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:white;\n"
"")
        self.label_6.setObjectName("label_6")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 340, 231, 19))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radioButton_8 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_4)
        self.radioButton_8.setStyleSheet("color:white;")
        self.radioButton_8.setObjectName("radioButton_8")
        self.horizontalLayout_5.addWidget(self.radioButton_8)
        self.radioButton_9 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_4)
        self.radioButton_9.setStyleSheet("color:white;")
        self.radioButton_9.setObjectName("radioButton_9")
        self.horizontalLayout_5.addWidget(self.radioButton_9)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(460, 340, 181, 31))
        self.pushButton.setObjectName("pushButton")
        self.label.raise_()
        self.horizontalLayoutWidget.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.horizontalLayoutWidget_3.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.progressBar.raise_()
        self.label_6.raise_()
        self.horizontalLayoutWidget_4.raise_()
        self.pushButton.raise_()
        self.pushButton.clicked.connect(self.jop)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.progressBar.hide()


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.radioButton_2.setText(_translate("Dialog", "Нет"))
        self.radioButton.setText(_translate("Dialog", "Да"))
        self.radioButton_5.setText(_translate("Dialog", "99999999+"))
        self.radioButton_4.setText(_translate("Dialog", "1-2"))
        self.radioButton_3.setText(_translate("Dialog", "0"))
        self.radioButton_7.setText(_translate("Dialog", "3"))
        self.radioButton_6.setText(_translate("Dialog", "Нет"))
        self.label_2.setText(_translate("Dialog", "Тест на дединсайда"))
        self.label_3.setText(_translate("Dialog", "Играешь ли ты в доту?"))
        self.label_4.setText(_translate("Dialog", "Сколько раз ты посмотрел токио гуль?"))
        self.label_5.setText(_translate("Dialog", "Знаешь ли ты сколько будет 1000-7"))
        self.label_6.setText(_translate("Dialog", "Больше вопросов я не придумал. Поставь класс"))
        self.radioButton_8.setText(_translate("Dialog", "Класс"))
        self.radioButton_9.setText(_translate("Dialog", "Класс"))
        self.pushButton.setText(_translate("Dialog", "Узнать насколько ты дединсайд"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
